# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Structure and content generally drawn from SocialServiceData.org, amended with
# a few quick quibbles.
tag_list = [
  [ 'emergency', 'emergency food', 'emergency food pantry' ],
  [ 'emergency', 'emergency food', 'emergency meals' ],
  [ 'emergency', 'domestic violence shelter' ],
  [ 'emergency', 'emergency shelter', 'family emergency shelter' ],
  [ 'emergency', 'emergency shelter', 'men\'s emergency shelter' ],
  [ 'emergency', 'emergency shelter', 'women\'s emergency shelter' ],
  [ 'emergency', 'emergency shelter', 'youth emergency shelter' ],
  [ 'emergency', 'hotline', 'crisis hotline' ],
  [ 'emergency', 'hotline', 'domestic violence hotline' ],
  [ 'emergency', 'hotline', 'shelter hotline' ],
  [ 'emergency', 'hotline', 'suicide hotline' ],
  [ 'family', 'children & youth', 'adoption' ],
  [ 'family', 'children & youth', 'baby supplies' ],
  [ 'family', 'children & youth', 'cash for childcare' ],
  [ 'family', 'children & youth', 'childcare' ],
  [ 'family', 'children & youth', 'diapers & formula' ],
  [ 'family', 'children & youth', 'finding childcare' ],
  [ 'family', 'children & youth', 'post incarceration support' ],
  [ 'family', 'children & youth', 'foster parenting' ],
  [ 'family', 'children & youth', 'foster youth' ],
  [ 'family', 'children & youth', 'parenting' ],
  [ 'family', 'children & youth', 'toys' ],
  [ 'family', 'children & youth', 'transitional age youth' ],
  [ 'family', 'clothes', 'baby clothes' ],
  [ 'family', 'clothes', 'cash for clothing' ],
  [ 'family', 'clothes', 'general clothes' ],
  [ 'family', 'clothes', 'school clothes' ],
  [ 'family', 'clothes', 'work clothes' ],
  [ 'family', 'domestic violence', 'domestic violence help' ],
  [ 'family', 'family support', 'case management' ],
  [ 'family', 'family support', 'mediation' ],
  [ 'family', 'family support', 'support for immigrants' ],
  [ 'family', 'household', 'cash for utilities' ],
  [ 'family', 'household', 'furniture' ],
  [ 'family', 'household', 'heating & cooling' ],
  [ 'family', 'household', 'household supplies' ],
  [ 'family', 'household', 'internet access' ],
  [ 'family', 'household', 'maintenance & repairs' ],
  [ 'family', 'household', 'pet care assistance' ],
  [ 'family', 'household', 'phone services' ],
  [ 'family', 'safety', 'emergency safety' ], # What does this even mean?
  [ 'family', 'seniors', 'senior day program' ],
  [ 'family', 'seniors', 'senior health care' ],
  [ 'family', 'seniors', 'senior housing' ],
  [ 'family', 'seniors', 'senior home care' ],
  [ 'family', 'veterans', 'veterans health benefits' ],
  [ 'family', 'veterans', 'veterans housing' ],
  [ 'family', 'veterans', 'veterans job placement' ],
  [ 'food', 'food education', 'nutrition' ],
  [ 'food', 'groceries', 'cash for food' ],
  [ 'food', 'groceries', 'food pantry' ],
  [ 'food', 'meals', 'food delivery' ],
  [ 'food', 'meals', 'free meals' ],
  [ 'food', 'meals', 'summer free lunch' ],
  [ 'health', 'addiction', 'alcohol' ],
  [ 'health', 'addiction', 'detox' ],
  [ 'health', 'addiction', 'drugs' ],
  [ 'health', 'addiction', 'needle exchange' ],
  [ 'health', 'addiction', 'other addictions' ],
  [ 'health', 'addiction', 'residential treatment' ],
  [ 'health', 'addiction', 'sober living' ],
  [ 'health', 'dental,' 'dental care' ],
  [ 'health', 'disabilities', 'adult daycare' ],
  [ 'health', 'disabilities', 'assisted living' ],
  [ 'health', 'disabilities', 'assistive technology' ],
  [ 'health', 'disabilities', 'disability benefits' ],
  [ 'health', 'disabilities', 'nursing facility' ],
  [ 'health', 'disabilities', 'work with disabilities' ],
  [ 'health', 'disabilities', 'recreation with disabilities' ],
  [ 'health', 'disabilities', 'disability advocacy & referral' ],
  [ 'health', 'end of life', 'burial & funeral help' ],
  [ 'health', 'end of life', 'hospice' ],
  [ 'health', 'end of life', 'in home support' ],
  [ 'health', 'health care', 'cash for health care' ],
  [ 'health', 'health care', 'health insurance' ],
  [ 'health', 'health care', 'paying medical bills' ],
  [ 'health', 'health education', 'general health education' ],
  [ 'health', 'health education', 'sex education' ],
  [ 'health', 'hygiene', 'personal hygiene supplies' ],
  [ 'health', 'medical', 'abortion' ],
  [ 'health', 'medical', 'alternative medicine' ],
  [ 'health', 'medical', 'birth control' ],
  [ 'health', 'medical', 'general medical care' ],
  [ 'health', 'medical', 'hearing' ],
  [ 'health', 'medical', 'HIV care' ],
  [ 'health', 'medical', 'HIV housing' ],
  [ 'health', 'medical', 'HIV treatment' ],
  [ 'health', 'medical', 'LGBT health' ],
  [ 'health', 'medical', 'medical supplies' ],
  [ 'health', 'medical', 'medical test' ],
  [ 'health', 'medical', 'pain management' ],
  [ 'health', 'medical', 'pediatric medicine' ],
  [ 'health', 'medical', 'physical therapy' ],
  [ 'health', 'medical', 'pregnancy' ],
  [ 'health', 'medical', 'prescriptions' ],
  [ 'health', 'medical', 'sexual health' ],
  [ 'health', 'medical', 'STD test' ],
  [ 'health', 'medical', 'transportation for healthcare' ],
  [ 'health', 'medical', 'vaccinations' ],
  [ 'health', 'mental health', 'grief' ],
  [ 'health', 'mental health', 'LGBT support group' ],  # Recategorized.
  [ 'health', 'mental health', 'mental health care' ],
  [ 'health', 'mental health', 'mental health counseling' ],
  [ 'health', 'mental health', 'peer support' ],
  [ 'health', 'mental health', 'support group' ],
  [ 'health', 'vision', 'eye exams' ],
  [ 'health', 'vision', 'glasses & contacts' ],
  [ 'housing', 'affordable housing', 'affordable long-term housing' ],
  [ 'housing', 'affordable housing', 'finding housing' ],
  [ 'housing', 'affordable housing', 'independent living' ],
  [ 'housing', 'affordable housing', 'public housing' ],
  [ 'housing', 'homeless support', 'laundry' ],
  [ 'housing', 'homeless support', 'showers' ],
  [ 'housing', 'homeless support', 'storage' ],
  [ 'housing', 'homeless support', 'homeless support services' ],
  [ 'housing', 'homeowners', 'buyers or renters insurance' ],
  [ 'housing', 'homeowners', 'foreclosure' ],
  [ 'housing', 'homeowners', 'loan modification' ],
  [ 'housing', 'housing assistance', 'homebuying assistance' ],
  [ 'housing', 'housing assistance', 'housing vouchers' ],
  [ 'housing', 'housing assistance', 'supportive housing' ],
  [ 'housing', 'housing education', 'home buyer education' ],
  [ 'housing', 'housing education', 'housing advice' ],
  [ 'housing', 'shelter', 'emergency shelter' ],
  [ 'housing', 'shelter', 'short term shelter' ],
  [ 'housing', 'tenants', 'eviction help' ],
  [ 'housing', 'tenants', 'rent assistance' ],
  [ 'housing', 'tenants', 'renters insurance' ],
  [ 'housing', 'tenants', 'tenants rights' ],
  [ 'housing', 'transitional housing', 'transitional housing program' ],
  [ 'housing', 'transitional housing', 'halfway house' ],
  [ 'housing', 'transitional housing', 'transitional safe housing' ],
  [ 'housing', 'transitional housing', 'transitional shelter for victims' ],
  [ 'learning', 'beyond school', 'after school' ],
  [ 'learning', 'beyond school', 'arts' ],
  [ 'learning', 'beyond school', 'mentoring' ],
  [ 'learning', 'beyond school', 'recreation' ],
  [ 'learning', 'beyond school', 'study abroad' ],
  [ 'learning', 'education', 'back to school' ],
  [ 'learning', 'education', 'college' ],
  [ 'learning', 'education', 'financial aid' ],
  [ 'learning', 'education', 'finding a school' ],
  [ 'learning', 'education', 'free books' ],
  [ 'learning', 'education', 'GED' ],
  [ 'learning', 'education', 'literacy' ],
  [ 'learning', 'education', 'preschool' ],
  [ 'learning', 'education', 'school supplies' ],
  [ 'learning', 'education', 'special education' ],
  [ 'learning', 'education', 'transportation for school' ],
  [ 'learning', 'education', 'tutoring' ],
  [ 'learning', 'language', 'ESL classes' ],
  [ 'learning', 'language', 'translation & interpretation' ],
  [ 'learning', 'paying for school', 'scholarships' ],
  [ 'learning', 'paying for school', 'school expenses' ],
  [ 'learning', 'paying for school', 'student loans' ],
  [ 'learning', 'skills', 'computer class' ],
  [ 'learning', 'skills', 'computer lab' ],
  [ 'learning', 'skills', 'internships' ],
  [ 'learning', 'skills', 'life skills training' ],
  [ 'learning', 'summer', 'day camp' ],
  [ 'learning', 'summer', 'overnight camp' ],
  [ 'learning', 'summer', 'summer program' ],
  [ 'legal', 'after prison', 'post incarceration support' ],
  [ 'legal', 'family law', 'family law' ],
  [ 'legal', 'general legal', 'IDs & driver\'s license' ],
  [ 'legal', 'general legal', 'lawyers' ],
  [ 'legal', 'housing law', 'housing law' ],
  [ 'legal', 'immigration law', 'immigration law' ],
  [ 'legal', 'workplace law', 'discrimination' ],
  [ 'legal', 'workplace law', 'workers\' compensation' ],
  [ 'legal', 'workplace law', 'workers\' rights' ],
  [ 'money', 'cash benefits', 'cash benefits' ],
  [ 'money', 'credit', 'banking & credit unions' ],
  [ 'money', 'credit', 'bankruptcy' ],
  [ 'money', 'credit', 'credit counseling' ],
  [ 'money', 'credit', 'credit repair' ],
  [ 'money', 'credit', 'legal help with credit' ],
  [ 'money', 'credit', 'loans' ],
  [ 'money', 'financial education', 'financial literacy' ],
  [ 'money', 'financial education', 'savings' ],
  [ 'money', 'taxes', 'tax law' ],
  [ 'money', 'taxes', 'tax preparation' ],
  [ 'money', 'transit', 'cash for gas' ],
  [ 'money', 'transit', 'transit fare' ],
  [ 'money', 'transit', 'transportation assistance' ],
  [ 'money', 'unemployment', 'unemployment benefits' ],
  [ 'money', 'work', 'career counseling' ],
  [ 'money', 'work', 'finding work' ],
  [ 'money', 'work', 'interview training' ],
  [ 'money', 'work', 'job placement' ],
  [ 'money', 'work', 'job training' ],
  [ 'money', 'work', 'resume help' ],
  [ 'money', 'work', 'starting a small business' ],
  [ 'money', 'work', 'workplace rights' ] # How is this not 'general legal'?
]

tag_list.each do |area, category, tag|
  Tag.create( area: area, category: category, tag: tag )
end
